[package]
name = "chip8"
version = "0.1.0"
authors = ["Benjamin Diaz <benjamin.diaz@iunigo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.1"
